In [1]:
import numpy as np

In [2]:
a = [1,2,3,4,5,6]
b = []

for i in a:
    b.append(i**2)

print(b)

[1, 4, 9, 16, 25, 36]


In [3]:
a = [1,2,3,4,5,6]
b = []

for i in a:
    b.append(i+1)

print(b)

[2, 3, 4, 5, 6, 7]


In [6]:
v = np.array([1,2,3,4,5,6])

# print(v)

# print(type(v))

v1 = v + 1

print(v1)


[2 3 4 5 6 7]


In [9]:
# Vector Addition

v = np.array([1,2,3])
w = np.array([2,3,4])
r = v + w

print(r)

[3 5 7]


In [10]:
# Scalar Multiplication

v = np.array([1,2,3])
w = v ** 2

print(w)

[1 4 9]


In [11]:
v = np.arange(0,10)

print(v)

[0 1 2 3 4 5 6 7 8 9]


In [12]:
v = np.array([[ 2, 3],
             [1,2]
            ])

print(v.ndim)

2


In [19]:
v = np.linspace(0, 10, 100)
print(v)

[ 0.          0.1010101   0.2020202   0.3030303   0.4040404   0.50505051
  0.60606061  0.70707071  0.80808081  0.90909091  1.01010101  1.11111111
  1.21212121  1.31313131  1.41414141  1.51515152  1.61616162  1.71717172
  1.81818182  1.91919192  2.02020202  2.12121212  2.22222222  2.32323232
  2.42424242  2.52525253  2.62626263  2.72727273  2.82828283  2.92929293
  3.03030303  3.13131313  3.23232323  3.33333333  3.43434343  3.53535354
  3.63636364  3.73737374  3.83838384  3.93939394  4.04040404  4.14141414
  4.24242424  4.34343434  4.44444444  4.54545455  4.64646465  4.74747475
  4.84848485  4.94949495  5.05050505  5.15151515  5.25252525  5.35353535
  5.45454545  5.55555556  5.65656566  5.75757576  5.85858586  5.95959596
  6.06060606  6.16161616  6.26262626  6.36363636  6.46464646  6.56565657
  6.66666667  6.76767677  6.86868687  6.96969697  7.07070707  7.17171717
  7.27272727  7.37373737  7.47474747  7.57575758  7.67676768  7.77777778
  7.87878788  7.97979798  8.08080808  8.18181818  8

In [66]:
# Returns Random value between a specified interval

v = np.random.rand(10,5)
w = v

print(w)

[[0.80082233 0.74708992 0.69117265 0.26428857 0.18408488]
 [0.11396457 0.17916025 0.26666879 0.74120581 0.03220719]
 [0.89551203 0.34742516 0.3193805  0.31449442 0.45165742]
 [0.60646951 0.07545322 0.43615597 0.83251734 0.02016216]
 [0.87909346 0.45379098 0.54577956 0.69459611 0.85149236]
 [0.84045316 0.13424844 0.68382823 0.55050557 0.4121114 ]
 [0.86264241 0.93231121 0.66118207 0.73318843 0.49462764]
 [0.16105668 0.31137374 0.99608033 0.10548699 0.68956808]
 [0.80012166 0.29018026 0.53596698 0.92449563 0.55726604]
 [0.32022132 0.34041487 0.81015533 0.44760653 0.25930156]]


In [54]:
v = np.random.randn(20)
print(v)

[ 0.29131657  1.35151904 -1.78476634  0.80769705 -1.42029142  1.66495659
  0.09136523  1.18519874 -0.57526293  0.14005864 -1.11389071 -0.57284216
 -1.12018168 -0.75438631 -1.61151276  2.53315326  0.67692735  1.65698688
 -0.54805115  0.05416999]


In [65]:
# Generating integers using randint

v = np.random.randint(10, 20, size=(10,5))
print(v)


[[10 12 12 14 17]
 [19 15 10 17 11]
 [17 15 14 13 18]
 [13 16 15 19 10]
 [17 17 19 11 18]
 [15 11 11 19 11]
 [16 16 11 17 15]
 [15 16 17 16 10]
 [10 12 15 16 14]
 [14 19 15 12 11]]


In [72]:
v = np.zeros((10,5))

print(v)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [73]:
v = np.ones((10,5))

print(v)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [85]:
v = np.ones((10,5))
w = np.zeros((10,5))
# w = v.reshape(10,20)

z = np.concatenate((v,w), axis=1)

print(z)

[[1. 1. 1. 1. 1. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 0. 0. 0. 0. 0.]]


In [86]:
v = np.ones((10,5))
w = np.zeros((10,5))
# w = v.reshape(10,20)

z = np.concatenate((v,w), axis=0)

print(z)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [94]:
v = np.random.randint(10, 20, size=(10,5))

v

array([[19, 18, 16, 19, 13],
       [16, 13, 19, 13, 11],
       [13, 19, 12, 12, 18],
       [17, 13, 10, 17, 15],
       [10, 19, 16, 15, 17],
       [14, 11, 13, 13, 17],
       [12, 19, 17, 13, 18],
       [15, 11, 15, 12, 13],
       [17, 19, 17, 19, 16],
       [10, 13, 19, 10, 12]])

In [96]:
v = np.random.randint(10, 20, size=(10,5))

v.sum()
v.max()


19